version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'examplecqrs'      
      MYSQL_USER: 'cqrs'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9095:8080

volumes:
  my-db: